<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-06-04 06:29
=======
# Generated by Django 2.2 on 2019-06-04 06:42
>>>>>>> 201197eebf5f64c880a1622cdcbf986c85590ad5

import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('causes_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('gallery_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('events_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('volunteer_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('about_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('contact_banner', models.ImageField(default='default.png', upload_to='banner')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('id',))),
                ('description', models.TextField(blank=True, null=True)),
                ('cause_image', models.ImageField(default='default.png', upload_to='cause')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(default='https://www.facebook.com')),
                ('twitter_link', models.URLField(default='https://www.twitter.com')),
                ('insta_link', models.URLField(default='https://www.instagram.com')),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(default='https://www.yoursite.com')),
                ('map_link', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('id',))),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('time', models.TimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='events')),
                ('venue', models.CharField(blank=True, max_length=60, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('auto_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='gallery')),
                ('date', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('views', models.IntegerField(default=0)),
=======
                ('views', models.IntegerField(blank=True, default=0, null=True)),
>>>>>>> 201197eebf5f64c880a1622cdcbf986c85590ad5
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='image_title', unique_with=('id',))),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='moreimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SectionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='setting')),
                ('volunteer_image', models.ImageField(default='default.png', upload_to='setting')),
                ('volunteer_bg_image', models.ImageField(default='default.png', upload_to='setting')),
                ('volunteer_text', models.TextField(blank=True, null=True)),
                ('about_title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('about_image', models.ImageField(default='default.png', upload_to='about')),
                ('about_description', models.TextField()),
                ('login_bg', models.ImageField(default='default.png', upload_to='setting')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='testimonial')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('id',))),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='MoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='moreimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Gallery')),
            ],
        ),
>>>>>>> 201197eebf5f64c880a1622cdcbf986c85590ad5
    ]
