# Generated by Django 2.1.5 on 2019-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(default='https://www.facebook.com')),
                ('twitter_link', models.URLField(default='https://www.twitter.com')),
                ('insta_link', models.URLField(default='https://www.instagram.com')),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(default='https://www.yoursite.com')),
                ('map_link', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='setting')),
                ('volunteer_image', models.ImageField(default='default.png', upload_to='setting')),
                ('volunteer_bg_image', models.ImageField(default='default.png', upload_to='setting')),
                ('about_title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('about_image', models.ImageField(default='default.png', upload_to='about')),
                ('about_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
