# Generated by Django 2.2 on 2019-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
