# Generated by Django 2.1.5 on 2019-06-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
