# Generated by Django 2.2 on 2019-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
