# Generated by Django 2.2 on 2019-06-04 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_remove_moreimage_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreimage',
            name='image_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.Gallery'),
            preserve_default=False,
        ),
    ]
