# Generated by Django 2.1.5 on 2019-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20190531_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
