# Generated by Django 2.2 on 2019-06-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20190602_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
