# Generated by Django 2.2 on 2019-05-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20190530_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_image',
            field=models.ImageField(default='default.png', upload_to='setting'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='setting'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='volunteer_bg_image',
            field=models.ImageField(default='default.png', upload_to='setting'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='volunteer_image',
            field=models.ImageField(default='default.png', upload_to='setting'),
        ),
    ]
