# Generated by Django 2.1.5 on 2019-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20190531_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncomponent',
            name='volunteer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
