# Generated by Django 2.2 on 2019-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190530_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='volunteer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
