# Generated by Django 2.2 on 2019-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190603_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
