# Generated by Django 2.2 on 2019-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20190530_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='setting'),
        ),
    ]
