# Generated by Django 2.2 on 2019-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20190603_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncomponent',
            name='login_bg',
            field=models.ImageField(default='default.png', upload_to='setting'),
        ),
    ]
