# Generated by Django 2.2 on 2019-05-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20190531_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='cause_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='cause'),
        ),
        migrations.AlterField(
            model_name='causes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='causes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
