# Generated by Django 2.2 on 2019-05-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_auto_20190531_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='testimonial'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
