# Generated by Django 2.2 on 2019-05-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_auto_20190531_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
