# Generated by Django 2.2 on 2019-05-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_auto_20190531_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
