# Generated by Django 2.2 on 2019-05-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_auto_20190531_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Causes',
            new_name='Cause',
        ),
    ]
