# Generated by Django 2.2 on 2019-05-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_auto_20190531_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
