# Generated by Django 2.2 on 2019-05-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanskarSamaj', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='VolunteerForm',
        ),
    ]
