# Generated by Django 2.1.5 on 2019-05-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanskarSamaj', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Causes',
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.RemoveField(
            model_name='moreimage',
            name='image_title',
        ),
        migrations.DeleteModel(
            name='Nav',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='VolunteerForm',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='MoreImage',
        ),
    ]
